#'''Parameters config.'''#


# --- binning_algorithms --- #

min_contig_len:   50


# --- concoct_binning --- #

fragment_size:    50
overlap_size:     0


# --- vamb_binning --- #

min_bin_size: 100
# Test-only-values: '-e 2 -t 2 -q 1'
# Keep blank for actual runs
test_flags: '-e 2 -t 2 -q 1'


# --- maxbin2_binning --- #

maxbin2_script: ''


# --- das_tool_refinement --- #

ext: ''
